# Generated by Django 5.2.6 on 2025-09-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_departments_dep_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
    ]
