# Generated by Django 5.2.4 on 2025-09-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='logins',
        ),
    ]
