# Generated by Django 5.2.4 on 2025-09-17 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_login_logins'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='logins',
            new_name='Userlogin',
        ),
    ]
