# Generated by Django 5.2.4 on 2025-09-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_logins_userlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='p_age',
            field=models.IntegerField(default=0),
        ),
    ]
