# Generated by Django 5.2.4 on 2025-09-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_booking_p_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='p_email',
        ),
    ]
