# Generated by Django 5.2.4 on 2025-09-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_booking_p_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('pin', models.CharField(max_length=20)),
            ],
        ),
    ]
