# Generated by Django 5.2.4 on 2025-09-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='address',
            new_name='paddress',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='age',
            new_name='page',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='pname',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='phone',
            new_name='pphone',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pin',
            new_name='ppin',
        ),
    ]
