# Generated by Django 5.2.4 on 2025-09-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_address_patient_paddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pcity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pstate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
