# Generated by Django 5.2.4 on 2025-09-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_patient_pcity_patient_pstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='paddress',
            field=models.CharField(max_length=100),
        ),
    ]
