# Generated by Django 5.2.4 on 2025-09-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_patient_paddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='regno',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
